# Template config using a public DoH server

[resolvers.doh-resolver]
address = "https://domain.com:port"
protocol = "doh"
transport = "quic"
enable-0rtt = false

[listeners.local-udp]
address = "127.0.0.4:53"
protocol = "udp"
resolver = "doh-resolver"
