# Template config using a public DoQ server

[resolvers.doh-resolver]
address = "https://2f07i9strpu.dns.controld.com.:443"
#address = "https://dns.adguard-dns.com/dns-query:443"
protocol = "doh"
transport = "quic"
enable-0rtt = false

[listeners.local-doh2]
address = "127.0.0.1:443"
protocol = "doh"
resolver = "doh-resolver"
server-crt = "example-config/server.crt"
server-key = "example-config/server.key"
