# Template config using a public DoQ server

[resolvers.doq-resolver]
address = "dns.adguard-dns.com:853"
protocol = "doq"
enable-0rtt = false

[listeners.local-doh2]
address = "127.0.0.5:443"
protocol = "doh"
resolver = "doh-resolver"
server-crt = "example-config/server.crt"
server-key = "example-config/server.key"
