# Template config using a public DoQ server

[resolvers.dou-resolver]
address = "2f07i9strpu.dns.controld.com.:53"
#address = "94.140.14.14:53"
protocol = "udp"

[listeners.local-doh2]
address = "127.0.0.3:443"
protocol = "doh"
resolver = "dou-resolver"
server-crt = "example-config/server.crt"
server-key = "example-config/server.key"
