# Template config using a public DoQ server

[resolvers.doh-resolver]
address = "https://domain.com:port"
protocol = "doh"
transport = "quic"
enable-0rtt = true

[listeners.local-udp]
address = "127.0.0.2:53"
protocol = "udp"
resolver = "doh-resolver"
