# Template config using a public DoQ server

[resolvers.doq-resolver]
address = "domain.com:port"
protocol = "doq"
enable-0rtt = false

[listeners.local-udp]
address = "127.0.0.3:53"
protocol = "udp"
resolver = "doq-resolver"
